from omni.isaac.orbit.actuators.group import ActuatorGroupCfg
from omni.isaac.orbit.actuators.group.actuator_group_cfg import ActuatorControlCfg
from omni.isaac.orbit.actuators.model import ImplicitActuatorCfg
from omni.isaac.orbit.robots.single_arm import SingleArmManipulatorCfg
from omni.isaac.orbit.robots.mobile_manipulator import MobileManipulator
from omni.isaac.orbit.robots.mobile_manipulator import MobileManipulatorCfg

PEPPER_USD_PATH="/home/cjf/Desktop/Isaac/orbit/Orbit/Asset/pepper_description/urdf/pepper/pepper.usd"

PEPPER_CFG = MobileManipulatorCfg(
    meta_info=MobileManipulatorCfg.MetaInfoCfg(
        usd_path=PEPPER_USD_PATH,
	base_num_dof=3,
	arm_num_dof=45,
	tool_num_dof=0,
	#tool_sites_names=["LFinger13_link",
			  #"LFinger23_link",
			  #"LFinger33_link",
			  #"LFinger43_link",
			  #"LThumb2_link",
			  #"RFinger13_link",
			  #"RFinger23_link",
			  #"RFinger33_link",
			  #"RFinger43_link",
			  #"RThumb2_link"], 
    ),
    init_state=MobileManipulatorCfg.InitialStateCfg(
        dof_pos={
            # pepper base
	   "XDisp": 0.0,
	   "YDisp": 0.0,
	   "ZRot": 0.0,
            # pepper body
	   "KneePitch": 0.0,
	   "HipPitch": 0.0,
	   "HipRoll": 0.0,
           "HeadPitch": 0.0,
           "HeadYaw": 0.0,
            # pepper left arm
           "LShoulderPitch": 0.0,
	   "LShoulderRoll": 0.0,
	   "LElbowYaw": 0.0,
	   "LElbowRoll": 0.0,
           "LWristYaw": 0.0,
	    # pepper right arm
           "RShoulderPitch": 0.0,
	   "RShoulderRoll": 0.0,
	   "RElbowYaw": 0.0,
	   "RElbowRoll": 0.0,
           "RWristYaw": 0.0,
	    # pepper left hand
	   "LFinger11": 0.0,
	   "LFinger21": 0.0,
           "LFinger31": 0.0,
           "LFinger41": 0.0,
	   "LHand": 0.0,
	   "LFinger12": 0.0,
	   "LFinger22": 0.0,
	   "LFinger32": 0.0,
	   "LFinger42": 0.0,
	   "LFinger13": 0.0,
	   "LFinger23": 0.0,
	   "LFinger33": 0.0,
	   "LFinger43": 0.0,
	   "LThumb1": 0.0,
	   "LThumb2": 0.0,
	    # pepper right hand
	   "RFinger11": 0.0,
	   "RFinger21": 0.0,
           "RFinger31": 0.0,
           "RFinger41": 0.0,
	   "RHand": 0.0,
	   "RFinger12": 0.0,
	   "RFinger22": 0.0,
	   "RFinger32": 0.0,
	   "RFinger42": 0.0,
	   "RFinger13": 0.0,
	   "RFinger23": 0.0,
	   "RFinger33": 0.0,
	   "RFinger43": 0.0,
	   "RThumb1": 0.0,
	   "RThumb2": 0.0,
        },
        dof_vel={".*": 0.0},
    ),
    ee_info=MobileManipulatorCfg.EndEffectorFrameCfg(
        body_name="Head", rot_offset=(1.0, 0.0, 0.0, 0.0)
    ),
    rigid_props=SingleArmManipulatorCfg.RigidBodyPropertiesCfg(
        max_depenetration_velocity=5.0,
    ),
    collision_props=SingleArmManipulatorCfg.CollisionPropertiesCfg(
        contact_offset=0.005,
        rest_offset=0.0,
    ),
    articulation_props=SingleArmManipulatorCfg.ArticulationRootPropertiesCfg(
        enable_self_collisions=True,
    ),
    actuator_groups={
        "pepper_base": ActuatorGroupCfg(
            dof_names=["XDisp",
		       "YDisp",
		       "ZRot",
		      ],
            model_cfg=ImplicitActuatorCfg(velocity_limit=1000.0, torque_limit=1000.0),
            control_cfg=ActuatorControlCfg(
                command_types=["v_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                #dof_pos_offset={
                    #"XDisp": 0.0,
                    #"YDisp": 0.0,
                    #"ZRot": 0.0,
                #},
            ),
        ),
        "pepper_body": ActuatorGroupCfg(
            dof_names=["KneePitch",
		       "HipPitch",
		       "HipRoll",
                       "HeadPitch",
                       "HeadYaw",],
            model_cfg=ImplicitActuatorCfg(velocity_limit=100.0, torque_limit=87.0),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                #dof_pos_offset={"KneePitch":-10.0,
				#"HipRoll": 0.0, 
				#"HipPitch": 10.0, 
				#"HeadPitch": 0.0, 
				#"HeadYaw":0.0,
		#},
            ),
        ),
        "pepper_L_arm": ActuatorGroupCfg(
            dof_names=["LShoulderPitch",
		       "LShoulderRoll",
	               "LElbowYaw",
		       "LElbowRoll",
		       "LWristYaw",
	               ],
            model_cfg=ImplicitActuatorCfg(velocity_limit=50.0, torque_limit=54.0),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                dof_pos_offset={"LShoulderPitch": 2.0, 
				#"LShoulderRoll": 0.0,
				#"LElbowYaw": 0.0,
				#"LElbowRoll": 0.0,
				#"LWristYaw": 0.0,
		},
            ),
        ),
	"pepper_R_arm": ActuatorGroupCfg(
            dof_names=["RShoulderPitch",
		       "RShoulderRoll",
	               "RElbowYaw",
		       "RElbowRoll",
		       "RWristYaw",
	               ],
            model_cfg=ImplicitActuatorCfg(velocity_limit=50.0, torque_limit=54.0),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                dof_pos_offset={"RShoulderPitch": 2.0, 
				#"RShoulderRoll": 0.0,
				#"RElbowYaw": 0.0,
				#"RElbowRoll": 0.0,
				#"RWristYaw": 0.0,
		},
            ),
        ),
        "pepper_L_hand": ActuatorGroupCfg(
            dof_names=["LFinger11",
		       "LFinger21",
	               "LFinger31",
		       "LFinger41",
		       "LHand",
		       "LFinger12",
		       "LFinger22",
	               "LFinger32",
		       "LFinger42",
		       "LFinger13",
		       "LFinger23",
	               "LFinger33",
		       "LFinger43",
	               "LThumb1",
	               "LThumb2",
		      ],
            model_cfg=ImplicitActuatorCfg(velocity_limit=50.0, torque_limit=10.0),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                #dof_pos_offset={"LFinger11": 0.0, 
				#"LFinger12": 0.0,
				#"LFinger13": 0.0,
				#"LFinger21": 0.0,
				#"LFinger22": 0.0,
				#"LFinger23": 0.0,
				#"LFinger31": 0.0,
				#"LFinger32": 0.0,
				#"LFinger33": 0.0,
				#"LFinger41": 0.0,
				#"LFinger42": 0.0,
				#"LFinger43": 0.0,
				#"LThumb1": 0.0,
				#"LThumb2": 0.0,
				#"LHand": 0.0,
		#},
            ),
        ),

        "pepper_R_hand": ActuatorGroupCfg(
            dof_names=["RFinger11",
		       "RFinger21",
	               "RFinger31",
		       "RFinger41",
		       "RHand",
		       "RFinger12",
		       "RFinger22",
	               "RFinger32",
		       "RFinger42",
		       "RFinger13",
		       "RFinger23",
	               "RFinger33",
		       "RFinger43",
	               "RThumb1",
	               "RThumb2",
		      ],
            model_cfg=ImplicitActuatorCfg(velocity_limit=50.0, torque_limit=10.0),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 800.0},
                damping={".*": 400.0},
                #dof_pos_offset={"RFinger11": 0.0, 
				#"RFinger12": 0.0,
				#"RFinger13": 0.0,
				#"RFinger21": 0.0,
				#"RFinger22": 0.0,
				#"RFinger23": 0.0,
				#"RFinger31": 0.0,
				#"RFinger32": 0.0,
				#"RFinger33": 0.0,
				#"RFinger41": 0.0,
				#"RFinger42": 0.0,
				#"RFinger43": 0.0,
				#"RThumb1": 0.0,
				#"RThumb2": 0.0,
				#"RHand": 0.0,
		#},
            ),
        ),
    },
)
